public with sharing class ContactTriggerHandler {
    /*private boolean isExecuting = false;
    private integer batchSize = 0;
    
    public ContactTriggerHandler(boolean isExecuting, integer size)
    {
        this.isExecuting = isExecuting;
        batchSize = size;
    }

    public void OnBeforeDelete(List<Contact> oldConts, Map<ID, Contact> oldContMap)
    {
        List<Case> cases = DeleteObjectsHelper.getCasesForContacts(oldContMap.keySet());
        DeleteObjectsHelper.removeContactFromCases(cases);
    }          

    public boolean IsTriggerContext
    {
        get{ return isExecuting;}
    }*/
}